language: node_js
os:
 - linux
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
  - 'if [ -n "${JEST}" ]; then npm run install:jest; fi'
script:
  - 'if [ -n "${PRETEST-}" ]; then npm run pretest ; fi'
  - 'if [ -n "${POSTTEST-}" ]; then npm run posttest ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage ; fi'
  - 'if [ -n "${JEST-}" ]; then npm run tests-only ; fi'
sudo: false
env:
  matrix:
    - JEST=18
    - JEST=19
    - JEST=20
    - JEST=21
    - JEST=22
    - JEST=23
    - JEST=24
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: PRETEST=true
    - node_js: "node"
      env: POSTTEST=true
  exclude:
    - node_js: "4"
      env: JEST=24
  allow_failures:
    - os: osx
